### PR TITLE
Multi-elevation & face normal placement

### PR DESCRIPTION
**Pull request by VertLinePoly**
I've added quickfire placement as well, looping out of finish() which terminates on cancel event, a parent rotation accumulator to handle parents without applied rotations. For standard placement (no wall or selected_cabinet) I've got it picking up the floor rotation so can get ortho placement in realworld settings (orientation not aligned to xy), maybe an align to custom transform orientations could be an option instead?

One last thing I'm gonna have a look at is picking up backside of cabinets to auto rotate back on themselves for island benches to avoid manual rotation settings. On the topic my install isn't catching arrow events for rotations.

Cursor is setting base elevation

### CODE REVIEW

**Comment by CreativeDesigner3D** [comment]
There is really great stuff here! I am still testing, but so far I am only running into a couple of issues. 

- When your cursor is not over an object you will get an error because the accumulate_z_rotation function expects an object. This isn't common, but if a user tries to drop a cabinet in front view it shouldn't return an error.
- I get strange results when placing a cabinet on a wall when the 3D cursor z is not at 0.

I'll continue to test this. Thank you so much for your work!

**Comment by PCON82** [comment]
Good spot, I had only tested free view where the drawing plane was picking up the ray cast, an ‘if selected_obj’ will work here as the accumulated only relevant if there is an object, I’ll add it in.

With the cursor I have set it to denote which floor I want to use. If you add a horizontal plane at z non zero, draw your walls on it, keep the cursor at that floor height everything works for that height, do same thing again at second storey of house and the placement will happen dependant on which floor the cursor is on. Also allows for continuous mesh representing split slab, one object with two different floor heights (step in slab). Again just place cursor on floor in the area you want to work in.

This method is not going to be everyone’s cup of tea but is definitely the easiest way to get multi elev, I’m imagining the others way is to setup floor class and to toggle the floor number you are working on at any given time. Otherway for floor obj to parent walls etc. but won’t work for non-home builder meshes. For me I already use cursor massively to navigate so is natural for my style.

Cheers

**Comment by CreativeDesigner3D** [comment]
I wanted to merge this in for the new release that is coming, but I wanted to check if you were going to make any changes for the issue when no object is selected. I can always make the changes when merging if you don't have time. I am planning on freezing all commits on the 9th, so if you don't have time then i'll make the changes. Thanks for your work!

**Comment by PCON82** [comment]
Have made the change in there so you should be good to go. And no worries, thanks for the addon and assets in the first place.

I'm still keen to take a look at picking up the snap to back of island cabinet but won't be in the next little while, I'll let you know how I go.

**Comment by PCON82** [comment]
Just added some additional comments around line 219 the if selectecte_normal.z == 0 as also returning 0 when selected_obj is None. No issue, just to clarify further

**Comment by PCON82** [comment]
Just made two last changes, first is blocking confirm_placement when no selected_obj by addition of self.drop which gets queried on left mouse click. If don't block, it drops it at 0,0 and flips. Most certainly could drop and fix rotation but it may end up in the swimming pool dependant on the scene.

The other being the back to back cabinet placement, this works really nice for creating the island benches. Had to modify the z accumulator to get it to work. The only way I can get sole consistent reference to back of cabinet is through the parent rotation (first parent/direct parent) of the back part of carcass which is half pi (or near enough) and all other sides 0.

Just out of curiosity, have you got any idea why the cabinet.draw() method (in particular add_insert and add_counter) gets incremently slower the more cabinets in the scene, its not a resource thing, I was hoping saving and reopening was going to clear some cache but doesn't reset the speed of it, maybe coming from add_assembly method (pc_types.Assembly())? I can add a shed load of fridges and it doesn't slow up at all.

Anyway I'll leave it here and thanks again for Home Builder its an impressive bit of kit.

**Comment by CreativeDesigner3D** [comment]
This has been merged. Thanks for your effort. This is a great improvement! I made a small change when cabinets are being placed on Home Builder walls. Let me know if you run into any issues with your workflow. 

The cabinet draw function becoming inclemently slower is probably because there are more objects and drivers that are added to cabinets that contain the manufacturing information. I will be creating an optimized cabinet library that only contains the design information to speed this up, but if you come across a way to optimize this let me know.

**Pull request merged**
